spring.datasource.url=jdbc:postgresql://localhost:5432/login_db
spring.datasource.username=username
spring.datasource.password=password

wg.server.endpoint=192.168.0.10:51820
wg.server.public-key=test_key_01

