CREATE SEQUENCE USER_SEQ
	START WITH 1 
	INCREMENT BY 1 
	NO MAXVALUE
;

CREATE TABLE USERS (
	ID BIGINT NOT NULL DEFAULT NEXTVAL('USER_SEQ'),
	LOGIN		VARCHAR(255) NOT NULL,
	PASSWD		VARCHAR(255) NOT NULL,
	AUTH_ROLE	VARCHAR(255) NOT NULL,
	ENABLED		BOOLEAN NOT NULL DEFAULT TRUE,
	ADDED_TS	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_TS	TIMESTAMP	
);

ALTER TABLE USERS ADD CONSTRAINT PK_USER PRIMARY KEY (ID)
;

CREATE UNIQUE INDEX UN_USER_LOGIN ON USERS ( UPPER( LOGIN ) )
;

CREATE OR REPLACE FUNCTION UPDATE_PROC() RETURNS TRIGGER AS $BODY$
    BEGIN
	IF (TG_OP = 'UPDATE') THEN
	      SELECT CURRENT_TIMESTAMP INTO NEW.MODIFIED_TS;
	END IF;
	RETURN NEW;
    END;
$BODY$ LANGUAGE plpgsql;


CREATE TRIGGER USER_UPD_TRG
 BEFORE UPDATE ON USERS
 FOR EACH ROW EXECUTE PROCEDURE UPDATE_PROC();
 
 
 
 
drop TABLE USERS; 
drop SEQUENCE USER_SEQ;
