CREATE OR REPLACE FUNCTION UPDATE_PROC() RETURNS TRIGGER AS $BODY$
    BEGIN
	IF (TG_OP = 'UPDATE') THEN
	      SELECT CURRENT_TIMESTAMP INTO NEW.MODIFIED_TS;
	END IF;
	RETURN NEW;
    END;
$BODY$ LANGUAGE plpgsql;


---------- USERS -----------


CREATE SEQUENCE USER_SEQ
	START WITH 1 
	INCREMENT BY 1 
	NO MAXVALUE
;

CREATE TABLE USERS (
	ID BIGINT NOT NULL DEFAULT NEXTVAL('USER_SEQ'),
	LOGIN		VARCHAR(255) NOT NULL,
	PASSWD		VARCHAR(255) NOT NULL,
	AUTH_ROLE	VARCHAR(255) NOT NULL,
	ENABLED		BOOLEAN NOT NULL DEFAULT TRUE,
	ADDED_TS	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_TS	TIMESTAMP	
);

ALTER TABLE USERS ADD CONSTRAINT PK_USER PRIMARY KEY ( ID )
;

CREATE UNIQUE INDEX UN_USER_LOGIN ON USERS ( UPPER( LOGIN ) )
;


CREATE TRIGGER USER_UPD_TRG
 BEFORE UPDATE ON USERS
 FOR EACH ROW EXECUTE PROCEDURE UPDATE_PROC();
 
 

 ---------- DEVICE -----------
 
CREATE SEQUENCE DEVICE_SEQ
	START WITH 1 
	INCREMENT BY 1 
	NO MAXVALUE
;

CREATE TABLE DEVICE (
	ID BIGINT NOT NULL DEFAULT NEXTVAL('DEVICE_SEQ'),
	USER_ID		BIGINT NOT NULL,
	DESCRIPTION	VARCHAR(1024),
	PUBLIC_KEY	TEXT NOT NULL,
	PRIVATE_KEY	TEXT NOT NULL,
	CREATED_AT	BIGINT NOT NULL,
	UPDATED_AT	BIGINT NOT NULL,
	EXPIRES_AT	BIGINT NOT NULL,
	ENABLED		BOOLEAN NOT NULL DEFAULT TRUE,
	PREFIX_LENGTH	SMALLINT NOT NULL CHECK (prefix_length IN (128, 64, 56, 48, 32)) DEFAULT 128,
	IP_PREFIX_16	INTEGER NOT NULL,
	IP_PREFIX_32	INTEGER NOT NULL,
	IP_PREFIX_32_48	INTEGER NOT NULL,
	IP_PREFIX_48_56	INTEGER NOT NULL,
	IP_PREFIX_56_64	INTEGER NOT NULL,
	IP_PREFIX_SLAAC	BIGINT NOT NULL,
	IP_ADDRESS	VARCHAR(40) NOT NULL,
	ADDED_TS	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_TS	TIMESTAMP	
);

ALTER TABLE DEVICE ADD CONSTRAINT PK_DEVICE PRIMARY KEY ( ID )
;

ALTER TABLE DEVICE ADD CONSTRAINT FK_DEVICE_USER
    FOREIGN KEY ( USER_ID ) REFERENCES USERS ( ID )
;

CREATE INDEX IX_FK_DEVICE_USER ON DEVICE ( USER_ID )
;
CREATE UNIQUE INDEX UN_DEVICE_PUBLIC_KEY ON DEVICE ( PUBLIC_KEY )
;
CREATE UNIQUE INDEX UN_DEVICE_IP ON DEVICE ( IP_PREFIX_16, IP_PREFIX_32, IP_PREFIX_32_48, IP_PREFIX_48_56, IP_PREFIX_56_64, IP_PREFIX_SLAAC )
;


CREATE TRIGGER DEVICE_UPD_TRG
 BEFORE UPDATE ON DEVICE
 FOR EACH ROW EXECUTE PROCEDURE UPDATE_PROC();





-------- ROLLBACK ---------------
 
drop TABLE USERS; 
drop SEQUENCE USER_SEQ;

drop TABLE DEVICE; 
drop SEQUENCE DEVICE_SEQ;
