INSERT INTO PERMISSION (id, name) VALUES(1, 'GENERATE_64');
INSERT INTO PERMISSION (id, name) VALUES(2, 'GENERATE_56');
INSERT INTO PERMISSION (id, name) VALUES(3, 'GENERATE_48');
INSERT INTO PERMISSION (id, name) VALUES(4, 'GENERATE_32');
