spring:
  config:
    import: optional:file:../config/ums.properties
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false

server:
  port: 37889

logging:
  level:
    org.springframework.security: DEBUG
